apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: rajveersinghrajput/user-service:v1
          imagePullPolicy: Always
          env:
            - name: AUTH_SERVICE_VERIFY_URL
              value: http://auth-service:8000/verify
          ports:
            - containerPort: 8001
